set_variable:
  name: "Set Variable"
  description: "Send variable update to Uponor API"
  fields:
    var_name:
      name: "Variable Name"
      description: "Name of the variable"
      example: "sys_heat_cool_mode"
    var_value:
      name: "Variable Value"
      description: "Value of the variable"
      example: 0
